# Generated by Django 4.1.7 on 2023-05-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile_certifications_and_more'),
        ('course', '0003_lecture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lecture',
            new_name='CourseData',
        ),
    ]
