# Generated by Django 4.1.7 on 2023-06-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_enrollment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
    ]
